name: Release Quarto Extension

on:
  workflow_dispatch:
    inputs:
      version:
        type: choice
        description: "Version"
        required: false
        default: "patch"
        options:
          - "patch"
          - "minor"
          - "major"
      quarto:
        type: string
        description: "Quarto version"
        required: false
        default: "pre-release"
      post-render:
        type: boolean
        description: "Run post-render scripts"
        required: false
        default: true

permissions:
  contents: write
  pull-requests: write
  id-token: write
  pages: write

jobs:
  release:
    uses: mcanouil/quarto-workflows/.github/workflows/release-extension.yml@main
    secrets: inherit
    with:
      gh-app-id: ${{ vars.APP_ID }}
      version: "${{ github.event.inputs.version }}"
      formats: "mcanouil-html+academic mcanouil-revealjs+dark mcanouil-revealjs+light mcanouil-typst+dark+pro mcanouil-typst+light+pro mcanouil-typst+dark+aca mcanouil-typst+light+aca mcanouil-html"
      quarto: "${{ github.event.inputs.quarto }}"
      post-render: ${{ github.event.inputs['post-render'] }}
      tinytex: false
      r: true
      python: false
      julia: false
